### ISSUE TITLE
Err when the parameter of nni.uniform() has a negative number

### ISSUE THREAD

**Issue by Tokarev-TT-33** [Microsoft/nni#1031]
**Short summary about the issue/question**:
Error when I'm using nni.uniform() function with negative number such as """@nni.variable(nni.uniform(-5, 5), name=x)""".

**Brief what process you are following**: 
Error when I'm trying """@nni.variable(nni.uniform(-5, 5), name=x)""", but when i changed to """@nni.variable(nni.uniform(0, 5), name=x)""", no error occured.

The raised error is "RuntimeError: Smart parameter's argument must be number literals".

**How to reproduce it**: 

**nni Environment**:
- nni version: 0.6
- nni mode(local|pai|remote): local
- OS: ubuntu 16.04 LTS
- python version: 3.7.3
- is conda or virtualenv used?: Conda is used
- is running in docker?: No

**need to update document(yes/no)**:
No
**Anything else we need to know**:
My full python code is just as follows:
```
import numpy as np
'''@nni.get_next_parameter()'''
"""@nni.variable(nni.uniform(-5, 5), name=x)"""
x = 0
a = np.cos(x)
"""@nni.report_final_result(a)"""
```

**Comment by QuanluZhang** [comment]
@Tokarev-TT-33 thanks for raising this issue. This is a bug of nni annotation. This bug is that -5 is not ast.Num but UnaryOp(op=Sub(), operand=Num(n=5)). We will fix this bug soon. The work-around is to remove line 90 in https://github.com/Microsoft/nni/blob/master/tools/nni_annotation/search_space_generator.py#L90. After you installed nni, this `search_space_generator.py` is under ~/.local/lib/python3.x/site-packages/nni_annotation/search_space_generator.py

**Comment by QuanluZhang** [comment]
The PR https://github.com/Microsoft/nni/pull/1040 fixes this bug.

**Comment by Tokarev-TT-33** [comment]
Bravo~!
