### ISSUE TITLE
any way to use more than one concurrency after raise NoMoreTrialError

### ISSUE THREAD

**Issue by YangZeyu95** [microsoft/nni#1225]
**Short summary about the issue/question**:
only one trail could be submitted after raise nni. NoMoreTrialError
**Brief what process you are following**: 
My tuner is based on population, and the number of individuals is not fix. So I use a list to store the individuals to be submitted. When generate_parameters is called,  tuner pop an individual from the list until it's empty and then raise nni. NoMoreTrialError. When there is no  trail is running, the list would be updated and enter the next circulation. The problem is that everytime  after  raise nn.iNoMoreTrialError the number of trails  at next circulation could only be one until turn up the concurrency in terminal or NNIBoard and the number of trails is the number been plused rather than concurrency  number. How to maintain the concurrency number after raise nni.NoMoreTrialError?

**How to reproduce it**: 

**nni Environment**:
- nni version: 0.8
- nni mode(local|pai|remote): local 
- OS: Ubuntu & MacOs
- python version: 3.6
- is conda or virtualenv used?: yes 
- is running in docker?: no

**need to update document(yes/no)**:
no
**Anything else we need to know**:
is that a bug or feature ?

**Comment by QuanluZhang** [comment]
@YangZeyu95 this is a good scenario. We internally discussed this scenario several times before.

First, NoMoreTrialError means "there is no trial anymore", does not mean "temporarily no more trial". In NNI's current implementation, each time the tuner issues NoMoreTrialError, the concurrency is reduced by one.

Second, here is a possible solution for your scenario: enable multi-thread for your experiment by adding `multiThread: true` in your experiment yml config file. When your tuner receives trial request but cannot generate a new trial immediately, you can simply wait in this function call until getting necessary information for generating the trial. This waiting will not block the tuner to run other function calls (e.g., `receive_trial_result`), because the tuner's methods run on different threads. We will add detailed document about how multiThread works and in what scenarios multiThread helps.

**Comment by scarlett2018** [comment]
@YangZeyu95 - had you tried the 2nd approach @quanluzhang mentioned above? would you mind share the results here?
