### ISSUE TITLE
Network morphism example can't run

### ISSUE THREAD

**Issue by xlthu** [microsoft/nni#1267]
**Short summary about the issue/question**:
Run example 'examples/trials/network_morphism/cifar10', then get
```
ERROR: NetworkMorphism should be installed through 'nnictl package install --name NetworkMorphism'
```

But, if I try to 'install NetworkMorphism', there cames
```
ERROR: NetworkMorphism is not supported!
```
And, accroding to the doc, I don't think we need to install NetworkMorphism before using it.

**How to reproduce it**: 

Clone the repo, install the lastest nni from pypi, and run the 'examples/trials/network_morphism/cifar10' example.
```
nnictl create -c config.yml
```

**nni Environment**:
- nni version: 0.9.1
- nni mode(local|pai|remote): local
- OS: ubuntu 16.04
- python version: python3.6
- is conda or virtualenv used?: no
- is running in docker?: no

**need to update document(yes/no)**: no

**Anything else we need to know**: Thanks a lot~

**Comment by xlthu** [comment]
nni==0.8.0 seems working fine, but I can't find it in pypi anymore.

**Comment by xuehui1991** [comment]
@xlthu thank you for your question.  Seems there might be a bug after we refine the installation code.
@leelaylay  could you help to check this problem? thanks.

**Comment by xlthu** [comment]
I think the reason is that `nni/networkmorphism_tuner/bayesian.py` imports `OptimizeMode` from wrong file.

Should be 
```
from nni.utils import OptimizeMode
```

But we have
```
from nni.networkmorphism_tuner.utils import Constant, OptimizeMode
```

[Code & Line here](https://github.com/microsoft/nni/blob/master/src/sdk/pynni/nni/networkmorphism_tuner/bayesian.py#L33)

Thank you~

**Comment by leelaylay** [comment]
@xlthu 
1. NetworkMorphism is one of the build-in tuners, so there is no need to install NetworkMorphism before using it. 
2. You are right. `OptimizeMode` class is imported from wrong file because the v0.9 code refactoring. If you want to use NetworkMorphism tuner, you can use nni branch `v0.8.1`.
```
# uninstall nni first
python3 -m pip uninstall nni

# from pip
python3 -m pip install nni==0.8.1

# or from source code
git clone -b v0.8.1 https://github.com/microsoft/nni.git
cd nni && make easy-install
```
I will fix this problem as soon as possible.

**Comment by leelaylay** [comment]
@xlthu 
The bug is fixed in the master branch and thank you.
And, `NetworkMorphism` is the build-in tuners which you don't need to install it. `SMAC` and `BOHB` are those tuners which you should install it by `nnictl package install --name package_name`.

If you want to know the python requirements of `NetworkMorphism`, you can see this file [requirements.txt](https://github.com/microsoft/nni/blob/master/examples/trials/network_morphism/requirements.txt).

**Comment by xlthu** [comment]
Thank you :grinning:

**Comment by xuehui1991** [comment]
The PR #1271  and #1272 have fix the bug and update the related doc.  @xlthu  thank you for you suggestion.
