### ISSUE TITLE
show all final results on webui when multiPhase is enabled

### ISSUE THREAD

**Issue by QuanluZhang** [microsoft/nni#1357]
**What would you like to be added**: when multiPhase is enabled, a trial job could run multiple trial configurations (e.g., hyperparameters). But in `Trials detail` page, only the last trial configuration's result of each trial job is shown in the figure.

**Why is this needed**: more friendly

**Without this feature, how does current nni work**：users could download `Experiment Parameters`, then parse this file and draw figures by themselves.

**Components that may involve changes**: webui

**Brief description of your proposal if any**: provide an option (e.g., a button) to users, making the figure to show all the final results.

**Comment by ultmaster** [comment]
Personally, I believe our multiPhase mode has two semantics.

1. A trial functions as a worker, in which case users use multiPhase mainly because they want to save the cost of launching a trial or preparing datasets or whatever. In this case, different parameters should have different rows in the table.

2. The algorithm needs it to be one single trial to share network weights or etc. In this case, it seems to me that the final result we want is the last final result. The rest of the results should be semantically "intermediate", instead of "final".

**Comment by scarlett2018** [comment]
Assign to @lvybriage for driving the discussion.

**Comment by Lijiaoa** [comment]
@scarlett2018 @QuanluZhang now nni support `reuse` mode, `multiphase` mode had been delete in webui. so I think this issue could be closed.

**Comment by Lijiaoa** [comment]
@kvartet Could you help close this issue?
