### ISSUE TITLE
Please support dashes in the config.yaml filename, or else report a meaningful error

### ISSUE THREAD

**Issue by daniel347x** [microsoft/nni#1540]
**Short summary about the issue/question**:

When I try to run NNI via `nnictl create --config ./config-user-scaling.yaml --port 8080`, nothing happens - there is no console message, and the command simply exits, leaving me back at the command prompt, wondering why the run did not occur.

**Brief what process you are following**: 

See above.

**How to reproduce it**: 

Create a config.yaml file with a filename that includes dashes, such as `config-user-scaling.yaml`.  Then, try to run the job at the command line.

**nni Environment**:
- nni version:
- nni mode(local|pai|remote):
- OS:
- python version:
- is conda or virtualenv used?: 
- is running in docker?:

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by SparkSnail** [comment]
Hi, I've tried a config file with dashes, but the experiment is started successfully. So I wonder if the problem is caused by OS or the content of yaml file.
If you remove the dashes in your yaml file, for example, change to config.yaml, can you run experiments successfully?
What is the OS are you using?
Could you paste the content of your yaml file here? I would check the content and have a try.
Thanks.

**Comment by ultmaster** [comment]
@daniel347x Any updates?

**Comment by scarlett2018** [comment]
Ping @daniel347x for comments =).

> Hi, @daniel347x I've tried a config file with dashes, but the experiment is started successfully. So I wonder if the problem is caused by OS or the content of yaml file.
> If you remove the dashes in your yaml file, for example, change to config.yaml, can you run experiments successfully?
> What is the OS are you using?
> Could you paste the content of your yaml file here? I would check the content and have a try.
> Thanks.

**Comment by daniel347x** [comment]
Thanks for looking into this, and apologies for not responding.  I'm
actually far from the NNI ecosystem right now - unfortunately - and do not
have my YAML on hand, and it would be a lot of work to reconstruct my
environment and system.

For that reason - if you can't reproduce - I'd close the issue for now.

Again, thanks!  I wish I could follow through, and I would if it were
easier for me to get this set back up.

Best,
Dan

**Comment by scarlett2018** [comment]
Hi @daniel347x thanks for the responds! Sorry to hear you are away from NNI, would you mind share more backgrounds? is it because of:
   A. you are no more need automl for your training work
   B. you find better alternative tools rather than NNI
If it is the later reason, would you mind to help us improve by telling more about which features we could do better =).
