### ISSUE TITLE
Got "Segmentation fault" when run make (reproducibility)

### ISSUE THREAD

**Issue by goooxu** [Microsoft/nni#174]
Followed the "How to contribute" document, and run the below commands:

1. `git clone https://github.com/Microsoft/nni.git`
2. `make install-dependencies`
3. `make build`
4. `make dev-install`
5. `nnictl create --config ~/nni/examples/trials/mnist/config.yml`

then, change some code, and run the 3rd and 4th command again, and got the below error

![image](https://user-images.githubusercontent.com/22703054/46597582-51ae6180-cb13-11e8-8baf-49dfc3ea9460.png)

**Comment by Crysple** [comment]
Hi goooxu
It is recommended for you to update you pip by `python3 -m pip install -U pip` even you don't need to change your pip version, because it is found that the pip of certain version installed through apt-get has some problems when installing some python dependencies of NNI. Further reason is unclear -- probably pip from these two source is different or the origin pip in your environment is somewhat broken or something else...
If you do want you keep your pip version, you can check your pip_version by `python3 -m pip -V` and then reinstall it again by `python3 -m pip install -U pip==pip_version`. This also works.

**Comment by Crysple** [comment]
Can solve it by using --no-cache-dir flag
refer to https://github.com/Microsoft/nni/wiki/FAQ
