### ISSUE TITLE
About NNI

### ISSUE THREAD

**Issue by knsong** [microsoft/nni#1743]
Hi, firstly thanks a lot for the great work. 
But I'm wondering what the main differences with [ray/tune](https://github.com/ray-project/ray#tune-quick-start) ？

**Comment by QuanluZhang** [comment]
@knsong thanks for asking. Ray is a great work. It is originally designed for easy scale-out of reinforcement learning algorithms. Then they support hyper-parameter tuning through the same distributed manner, because distributed reinforcement learning and hyper-parameter tuning can be easily unified in the same framework.

NNI is a pure AutoML toolkit for both hyper-parameter tuning and neural architecture search. NNI's position is helping users easily find good models, which includes good neural architecture, good hyper-parameters, good model compression approach, and possibly some other fancy features to help design good models in future.

Thus, according to me, a main difference is different positioning. There are also some other differences, for example, different back-end design, high extensibility, users could easily customize their own training services and tuning algorithms following simple interfaces.
