### ISSUE TITLE
nni run in openPAI

### ISSUE THREAD

**Issue by zlwzlwzlw** [microsoft/nni#1817]
**Short summary about the issue/question**: 
1.where to submit the command "nnictl create --config exp_pai.yml"
2.paiConfig:hostIp is deploy the openPAI host IP?
**Brief what process you are following**: 
my yaml file:
![image](https://user-images.githubusercontent.com/33961256/70125417-b92d5600-16b1-11ea-8fe7-1c4d5566241f.png)
running yaml
![image](https://user-images.githubusercontent.com/33961256/70126141-5b017280-16b3-11ea-9ef8-7c0a0f628972.png)

![image](https://user-images.githubusercontent.com/33961256/70125679-407ac980-16b2-11ea-9882-1e70fe5d0722.png)
how can i fix it,thanks

**How to reproduce it**: 

**nni Environment**:centos
- nni version:v1.2
- nni mode(local|pai|remote):
- OS:
-openPAI: v0.14
- python version:3.6
- is conda or virtualenv used?: 
- is running in docker?: 

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by SparkSnail** [comment]
Hi @zlwzlwzlw, this issue might caused by `eth0` device error. NNI use `eth0` to get your host IP, and communicate with webui. You could set `nniManagerIp` field in your config file to avoid this error. refer https://github.com/microsoft/nni/wiki/FAQ#job-management-error-getipv4address-failed-because-osnetworkinterfaceseth0-is-undefined, https://nni.readthedocs.io/en/latest/Tutorial/ExperimentConfig.html#configuration-spec.
For your question:
1. You could use `nnictl` command anywhere, as long as you set correct config file path in `--config` filed.
2. `host` is OpenPAI's host IP, like `10.151.12.13`

**Comment by zlwzlwzlw** [comment]
host IP is OpenPAI's master host IP? nniManagerIp is the one of openPAI work IP?

**Comment by ultmaster** [comment]
Host IP is the IP address where you access OpenPAI (yes, master IP). nniManagerIp is the IP address of the machine where you run `nnictl`. This is provided so that trial jobs on OpenPAI can send results back to nni manager.

**Comment by zlwzlwzlw** [comment]
it work,thankyou!
