### ISSUE TITLE
hit input type and weigh type runtimeerror while exporting onnx model

### ISSUE THREAD

**Issue by 205418367** [microsoft/nni#1925]
当代码执行到：pruner.export_model('model.pth', 'mask.pth', 'model.onnx', [1, 3, 224, 224])出错
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

**Comment by QuanluZhang** [comment]
@205418367 thanks for reporting this issue. I guess you are exporting onnx file. This is a bug in `export_model`, which will be fixed in the next release.

In detail, https://github.com/microsoft/nni/blob/v1.3/src/sdk/pynni/nni/compression/torch/compressor.py#L252 , here, `input_data` should be put on the same device as your model. Could add `input_data = input_data.to('cuda')` below that line if you are using gpu.

**Comment by QuanluZhang** [comment]
The fix (add `device` argument in `export_model`) has been included in master branch and will be released in v1.4: https://github.com/microsoft/nni/blob/master/src/sdk/pynni/nni/compression/torch/compressor.py#L304
