### ISSUE TITLE
NAS examples

### ISSUE THREAD

**Issue by maayan-hassidim** [microsoft/nni#1983]
Hi,

**Short summary about the issue/question**:
I'm trying to run a NAS example (classic_nas and also NNI-NAS-Example-dev-enas) and get errors.

**Brief what process you are following**: 
When running: nnictl create --config config_nas.yml I get the error: 
ERROR: Your config file is not correct, please check your config file content!
ERROR: searchSpacePath path not exist!

After a google search I found the NNI-NAS-Example-dev-enas from the dev-enas branch (https://github.com/Crysple/NNI-NAS-Example/tree/dev-enas) and added it to the nas example directory. 
When running nnictl create --config config.yml I get this error: 
![image](https://user-images.githubusercontent.com/24750856/73426024-ffaed200-433b-11ea-9a40-6236bc0181c3.png)

**How to reproduce it**: 

**nni Environment**:
- nni version: print(nni.__version__) doesn't work  
- nni mode(local|pai|remote): local 
- OS: linux
- python version: python 3.7.5
- is conda or virtualenv used?: conda 
- is running in docker?: no 

**need to update document(yes/no)**: no 

**Anything else we need to know**: no 

Thanks! 
Maayan

**Comment by ultmaster** [comment]
Hi. For your first question, please follow the instructions [here](https://nni.readthedocs.io/en/latest/NAS/NasInterface.html#classic-distributed-search): run `ss_gen` first, then `nnictl`.

It looks to me that the problem you show in your screenshot is caused by tensorflow. Try to downgrade your tensorflow.

Please also note that NNI-NAS-Example-dev-enas is a very old example, and not compatible with current API (or future). To use it, please install NNI <= 1.0.

Thanks for your issue and hope it works for you.

**Comment by maayan-hassidim** [comment]
Thanks! Now it works.
