### ISSUE TITLE
Runtime error in ENAS example code

### ISSUE THREAD

**Issue by weiT1993** [microsoft/nni#2083]
**Short summary about the issue/question**:
The ENAS example codes encountered a runtime error when switching Relu to SELU activation functions.

**Brief what process you are following**: 

**How to reproduce it**: 
In `nni/examples/nas/enas/ops.py`, switching all `nn.ReLu()` by `nn.SELU()`. Run `python search.py` as usual. The following error was encountered:
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [128, 24, 8, 8]], which is output 0 of EluBackward, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

**nni Environment**:
- nni version: 1.3
- nni mode(local|pai|remote): local
- OS: MacOS 10.15.3
- python version: 3.7
- is conda or virtualenv used?: Yes
- is running in docker?: No

**need to update document(yes/no)**: no

**Anything else we need to know**: NA

**Comment by ultmaster** [comment]
Hi. I'm not a PyTorch expert, so I looked it up. As suggested in [PyTorch forum](https://discuss.pytorch.org/t/elu-residual-unit-not-inplace-computation/13952), I should be looking for some inplace operation, like +=. It turns out there is one here:

https://github.com/microsoft/nni/blob/24fa4619cf01bc4279ff4ba2051bb73f8f049ee3/examples/nas/enas/macro.py#L35

After I changed `out += connection` to `out = out + connection`, it works.

Thanks for raising this issue, but I believe it's a pure PyTorch issue.

**Comment by weiT1993** [comment]
Thank you for looking into this. That solved the problem!
