### ISSUE TITLE
The document page for Mutable is lost.

### ISSUE THREAD

**Issue by marsggbo** [microsoft/nni#2128]
https://nni.readthedocs.io/en/latest/NAS/NasReference.md#mutables is lost.
Could you explain more about mutables?

**Comment by QuanluZhang** [comment]
@marsggbo thanks! will fix it.

**Comment by QuanluZhang** [comment]
@marsggbo the links are fixed by removing section reference, as sphinx does not support cross-file section reference in markdown.

Here I briefly explain `mutables`. You might be confused about the difference between `mutable` and `mutator`. NAS algorithms could use the same approach (i.e., same format) to express their own search space, but how to deal with search space are very different for different NAS algorithms. `mutable` mainly tackles the former part, it is a common interface (derivatives of `mutable`, e.g., `LayerChoice`, `InputChoice`) for specifying search space in model code, does not depend on any specific NAS algorithm. `mutator` mainly tackles the latter part. For a `LayerChoice`, NAS algorithms have different logic to handle it, for example DARTS connects all the choices into the model, ENAS sample one choice every minibatch. This can be seen as different interpretation of `LayerChoice`. That is why you can see `DartsMutator` `EnasMutator` in source code, but there is no `DartsMutable` or `EnasMutable`.
