### ISSUE TITLE
Port Question.

### ISSUE THREAD

**Issue by Hyyu0721** [microsoft/nni#2131]
After I finished an experiment with a port and delete it, how can I use this port again instead of using another port? 
BTW, can I change the port when an experiment is running?
Thank you!

**Comment by liuzhe-lz** [comment]
A port may need up to a minute to become reusable after released. This is due to the implementation in OS kernel. There is not much we can do.
However if the port is occupied for more than a minute, maybe your experiment is not correctly stopped.
Changing port on the fly is a very complicated feature so we have no plan on it. But you can stop the experiment and resume on another port if you have to.

**Comment by Hyyu0721** [comment]
Thank you for your reply!
