### ISSUE TITLE
Is Kubeflow mode not available on EKS ?

### ISSUE THREAD

**Issue by soochem** [microsoft/nni#2296]
**Short summary about the issue/question**:
Cloud dependency of kubeflow mode

**Brief what process you are following**: 
Hello, I am working on _distributed mnist example_ on kubeflow built on EKS.
I hope to use NFS provided by AWS (eg. elastic file system) and currently meet errors.
I have mounted a working directory(~/data-vol-1) of a jupyter instance through EFS persistence volume claim.
NNI API executed command sudo mount and failed because of insufficient permission.
I think kubeflow mode depends on Azure services such as AKS and Azure Storage.
If not, I'd like to resolve this NFS mounting error on EKS. Thanks.
  
Error message below:
`ERROR: Failed! Error is: {"error":"Mount NFS xxx.xxx.xxx:/ to /home/jovyan/data-vol-1/nni/MpQG1QBy/trials-nfs-tmp failed, error is ChildProcessError: Command failed: sudo mount xxx.xxx.xxx:/ /home/jovyan/data-vol-1/nni/MpQG1QBy/trials-nfs-tmp\nmount: /home/jovyan/data-vol-1/nni/MpQG1QBy/trials-nfs-tmp: permission denied.\n `sudo mount xxx.xxx.xxx:/ /home/jovyan/data-vol-1/nni/MpQG1QBy/trials-nfs-tmp` (exited with error code 32)"}`

**How to reproduce it**: 

**nni Environment**:
- nni version: 1.4
- nni mode(local|pai|remote): kubeflow
- OS: ubuntu 18.04.3
- python version: 3.6.8
- is conda or virtualenv used?: no
- is running in docker?: yes (tensorflow-py3-jupyter image)

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by SparkSnail** [comment]
Hi @soochem, NNI support using AzureStroage and NFS for stoage in kubeflow trainingService. In NFS mode, you should provide your NFS Server host and path, NNI will use `sudo mount server:/path {nni_temp_folder}` to mount the server for you, which means that you should have sudo permission in your current user. 
If you want to use AzureStorage instead of NFS, you can find instruction in https://github.com/microsoft/nni/blob/master/docs/en_US/TrainingService/KubeflowMode.md. 
NNI does not rely on AKS unless you use AzureStorage, NNI could work on EKS using NFS storage in theory.

**Comment by soochem** [comment]
Thank you for the kind advice. I think sudo permission is the main problem. I use an EC2 instance instead of jupyter notebook instance which is running on and provided by kubeflow and "sudo mount" worked! NNI kubeflow mode works fine with EKS & EFS. Thanks.
