### ISSUE TITLE
examples/nas/naive-tf Error:   File "train.py", line 82, in <module>     dataset_valid=dataset_valid,   File "/home/user/.local/lib/python3.6/site-packages/nni/nas/tensorflow/enas/trainer.py", line 39, in __init__     x, y = dataset_train ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Annika10** [microsoft/nni#2934]
**Environment**:
- NNI version: 1.8
- NNI mode (local|remote|pai): local
- Client OS: ubuntu 18.04
- Server OS (for remote mode only): -
- Python version: 3.8.6
- PyTorch/TensorFlow version: TensorFlow 2.3.1
- Is conda/virtualenv/venv used?: venv
- Is running in Docker?: no

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

The error message is: 
```
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    trainer = EnasTrainer(
  File "/home/user/venv/lib/python3.8/site-packages/nni/nas/tensorflow/enas/trainer.py", line 39, in __init__
    x, y = dataset_train
ValueError: too many values to unpack (expected 2)
```

**What issue meet, what's expected?**:
The naive-tf example doesn't run.

**How to reproduce it?**: 
Just run
`python3 train.py `
in examples/nas/naive-tf 

**Additional information**:
I comment `#dataset_test=dataset_test` because EnasTrainer doesn't have an argument dataset_test

**Comment by liuzhe-lz** [comment]
Sorry, I forgot to update the example after a refactor.
Correct `train.py` is [here](https://github.com/microsoft/nni/blob/c3ece8c789d8315c5909d099e41acc65c9cc2ecc/examples/nas/naive-tf/train.py).

**Comment by Annika10** [comment]
Thanks a lot :) That worked.

**Comment by Annika10** [comment]
I only have one question. How can I export the architecture? The EnasTrainer for Tensorflow doesn't have the method "export"

**Comment by Tudor33** [comment]
Good qostion   Odesláno z aplikace Pošta pro Windows 10 Od: Annika10Odesláno:úterý 20. října 2020 15:59Komu: microsoft/nniKopie: SubscribedPředmět: Re: [microsoft/nni] examples/nas/naive-tf Error: File "train.py", line 82, in <module> dataset_valid=dataset_valid, File "/home/user/.local/lib/python3.6/site-packages/nni/nas/tensorflow/enas/trainer.py", line 39, in __init__ x, y = dataset_train ValueError: too many values to unpack (expected 2) (#2934) I only have one question. How can I export the architecture? The EnasTrainer for Tensorflow doesn't have the method "export"—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Tudor33** [comment]
My engliš very bet ☹ 😃 and ai work and ai háve projekt big for every oarld   Odesláno z aplikace Pošta pro Windows 10 Od: Annika10Odesláno:úterý 20. října 2020 15:59Komu: microsoft/nniKopie: SubscribedPředmět: Re: [microsoft/nni] examples/nas/naive-tf Error: File "train.py", line 82, in <module> dataset_valid=dataset_valid, File "/home/user/.local/lib/python3.6/site-packages/nni/nas/tensorflow/enas/trainer.py", line 39, in __init__ x, y = dataset_train ValueError: too many values to unpack (expected 2) (#2934) I only have one question. How can I export the architecture? The EnasTrainer for Tensorflow doesn't have the method "export"—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by liuzhe-lz** [comment]
Exporting is not yet implemented  :(
NAS for TensorFlow is still under development.

**Comment by Annika10** [comment]
Sad, but thanks for the reply :) I will close this issue.
