### ISSUE TITLE
QuantGrad computation  in quantization is not correct

### ISSUE THREAD

**Issue by eedalong** [microsoft/nni#3159]
QuantGrad use STE for grad back propagation. STE, according to google's whitepaper, is computed by ![](http://119.3.255.23:8001/issue.jpg), but in current nni's implementation, its just quantize_grad = output_grad.

**Comment by eedalong** [comment]
I'll fix this in next pr

**Comment by linbinskn** [comment]
Thank you for your issue and PR.
This change may not be necessary because the grad_output is the grad of quantized weight(**W_out**) and all of the **W_out** have been in the range of **Wmin and Wmax** due to clamping during quantizing. Have you tested whether this change will bring extra advantages such as improving final accuracy or speeding up the model convergence during training or not?

**Comment by eedalong** [comment]
um

**Comment by eedalong** [comment]
The problem is solved, and pr is merged. So I will close this issue. Cheers Guys!
