### ISSUE TITLE
[Cream] Can't test pretrained models.

### ISSUE THREAD

**Issue by duchengyao** [microsoft/nni#3336]
When testing 14.pth.tar, error raised.
```
RuntimeError: Error(s) in loading state_dict for ChildNet:
        size mismatch for blocks.5.0.conv_dw.weight: copying a param with shape torch.Size([576, 1, 5, 5]) from checkpoint, the shape in current model is torch.Size([576, 1, 3, 3]).
```

To solved the problem,I convert [test.py#L86](https://github.com/microsoft/nni/blob/v2.0/examples/nas/cream/test.py#L86) from `ir_r1_k3_s2_e6_c192_se0.25` to `ir_r1_k5_s2_e6_c192_se0.25` following [microsoft/Cream/test.py#L85](https://github.com/microsoft/Cream/blob/main/tools/test.py#L85).

So, why this param from NNI is different from microsoft/Cream.

Thanks!

**Comment by Z7zuqer** [comment]
Hi,

Thank you for pointing out the definition bug of search space in the code. The solution to this problem is as you pointed out,  *microsoft/cream* will update slightly faster than the cream code in nni, and not merge in time, so this situation has occurred, and we will pay attention to keep updating.

Best,
Hao.
