### ISSUE TITLE
In quantization, why we must ensure that 0 is is in the activation/weight range.

### ISSUE THREAD

**Issue by chenbohua3** [microsoft/nni#3493]
In function `update_quantization_param`, there are two lines of codes:
```
rmin = torch.min(rmin, torch.Tensor([0]).to(rmin.device))
rmax = torch.max(rmax, torch.Tensor([0]).to(rmin.device))
```
I understand that if it is for quantization of activation, we must make sure that 0 is in the range, because there might be zero padding. However, if it is for quantization of weight, I can not figure out why we should keep 0 in the range.

**Comment by linbinskn** [comment]
Make sense! The implementation of current NNI quantization refers to [gemmlowp](https://github.com/google/gemmlowp/blob/fcf32e7a0a4d2af46e63eccf0c8fa4d83d0311c5/doc/quantization_example.cc) and it extends range to include 0 in both weights quantization and activation quantization. But it doesn't mean that this implementation is optimal. Since weights have nothing to do with padding, I think keeping the original min and max value maybe more reasonable. We will discuss it and find better way to handle it. We also look forward to your PR submission to improve this topic.

**Comment by chenbohua3** [comment]
I'll handle the topic later this weekend

**Comment by scarlett2018** [comment]
@chenbohua3 / @linbinskn / @ultmaster - has the above fixed got in the recent candidate release?

**Comment by J-shang** [comment]
close this issue because `this is a default behavior in PyTorch quantization observer.`
