### ISSUE TITLE
Does sensitivity pruner only support conv2d layers?

### ISSUE THREAD

**Issue by saikatG** [microsoft/nni#3826]
The pruner does not seem to be working with other layers e.g. `Linear`? `SensitivityPruner.py` contains the following code, which seems to only add conv2d layers.

```
def create_cfg():
...
  if sparsity > 0:
                # Pruner does not allow the prune ratio to be zero
                cfg = {'sparsity': sparsity, 'op_names': [
                    layername], 'op_types': ['Conv2d']}
                cfg_list.append(cfg)
```

**Comment by J-shang** [comment]
Yes, sensitivity pruner only supports `Conv2d` right now because most pruners used in `SensitivityPruner` only support `Conv2d`, i.e. `l1`, `l2`, `fpgm`. Do you want to use `level` to fine-grained pruning the model or other needs? We could discuss and find what we can do next to improve this pruner.

**Comment by saikatG** [comment]
Yes, I am using `level` pruning on (non-vision) models which dont have any `Conv2d` layers.
