### ISSUE TITLE
SimulatedAnnealing Pruner goes into infinite loop

### ISSUE THREAD

**Issue by saikatG** [microsoft/nni#3865]
Hi,

I found that the [Simulated Annealing Pruner](https://github.com/microsoft/nni/blob/v2.2/nni/algorithms/compression/pytorch/pruning/simulated_annealing_pruner.py) goes into an infinite loop when the target sparsity is >0.8. 

I observed that this mainly happens during initialization when it tries to generate sparsities in an [infinite loop](https://github.com/microsoft/nni/blob/3638072f4bb84666b0499c7fcf75122288fe3206/nni/algorithms/compression/pytorch/pruning/simulated_annealing_pruner.py#L211). For the randomly generated initial [sparsity vector](https://github.com/microsoft/nni/blob/3638072f4bb84666b0499c7fcf75122288fe3206/nni/algorithms/compression/pytorch/pruning/simulated_annealing_pruner.py#L213) , the actual sparsity is close to ~0.5-0.7. Hence, the [scale](https://github.com/microsoft/nni/blob/3638072f4bb84666b0499c7fcf75122288fe3206/nni/algorithms/compression/pytorch/pruning/simulated_annealing_pruner.py#L198)  is computed to be >1 for a large target sparsity (e.g. 0.8, 0.9). 

```python
    scale = target_sparsity / (total_weights_pruned/total_weights) # >1 for target > 0.8 or 0.9
    sparsities = np.asarray(sparsities)*scale  # max(sparsities) > 1
```

As a result this always fails the check in `init_sparsities` which requires the max to be <1. Hence the loop never breaks.
https://github.com/microsoft/nni/blob/3638072f4bb84666b0499c7fcf75122288fe3206/nni/algorithms/compression/pytorch/pruning/simulated_annealing_pruner.py#L218 

This does not depend on the input model though. Hope I could explain the issue clearly. Let me know if you need more details.

I looked at the paper, but it only says "Normalize by target sparsity C", which is quite ambiguous. Do you guys any suggestions on what could be the fix? I will be happy to make the change. Thanks!

Environment:
NNI 2.2
python 3.7

**Comment by J-shang** [comment]
Hi @saikatG 

Yes, it is hard to satisfy the constraint (you mentioned in L218) with a large target sparsity rate if we only depend on `random`, it may cost a long time to find an appropriate result, though it is what say in the paper.
https://github.com/microsoft/nni/blob/3638072f4bb84666b0499c7fcf75122288fe3206/nni/algorithms/compression/pytorch/pruning/simulated_annealing_pruner.py#L212-L213

An improvement might be increasing the lower limit of the `random` in the iteration, like that:
```
low_limit = 0
while True:
    low_limit = (1 - low_limit) * 0.05 + low_limit
    sparsities = sorted(np.random.uniform(low_limit, 1, len(self.get_modules_wrapper())))
    ...
```

This because the constraint can seem as:
`largest_sparsity / total_weights_pruned < 1 / (target_sparsity * total_weights)`
The left side is determined by randomness, the right side is a constant. So we can make the left smaller to satisfy the constraint.

But this change may make you lose some possibilities because the random range is changed. You can balance whether you want faster speed or more possibilities. And there are more ways to speed up along this line of thought, you could find one to satisfy your work.

If you have more idea, feel free to discuss with us.

**Comment by saikatG** [comment]
Yeah, I think this makes sense. It still respects the original requirement that layers with more weights should be pruned more and is pretty cheap.

**Comment by saikatG** [comment]
If you want, I can raise a PR to add this fix. Please let me know if you have any other suggestions as well.

**Comment by J-shang** [comment]
Hi @saikatG ,

Of course, you can raise a PR to improve this pruner, and due to this is not mentioned in the paper, please explain this in doc. Thanks for your contribution.
