### ISSUE TITLE
Why skip top-level module when detect modules to be compressed

### ISSUE THREAD

**Issue by chenbohua3** [microsoft/nni#4326]
The top level of the model is skipped when detect modules to be compressed (As seen [here](https://github.com/microsoft/nni/blob/3601044e9435edf1081eac5509f3e928876b11ca/nni/compression/pytorch/compressor.py#L95)). If we have a model like:
```
model = torch.nn.Linear(10, 20)
```
the linear layer can not be captured as the module to be compressed.

**Comment by J-shang** [comment]
If we want to wrap `model = torch.nn.Linear(10, 20)`, we need to specifically deal with this situation. This is because in this case `Pruner.bound_model = Wrapper(torch.nn.Linear)`.

https://github.com/microsoft/nni/blob/3601044e9435edf1081eac5509f3e928876b11ca/nni/compression/pytorch/compressor.py#L109

**Comment by scarlett2018** [comment]
> If we want to wrap `model = torch.nn.Linear(10, 20)`, we need to specifically deal with this situation. This is because in this case `Pruner.bound_model = Wrapper(torch.nn.Linear)`.
> 
> https://github.com/microsoft/nni/blob/3601044e9435edf1081eac5509f3e928876b11ca/nni/compression/pytorch/compressor.py#L109

@chenbohua3 - has the answer addressed your question?

**Comment by scarlett2018** [comment]
Closing the issue as overdue as it has no responds for a while, feel free to reopen if you are still seeing the problem on your side.
