### ISSUE TITLE
difference between AGPPruner and AGPTaskGenerator

### ISSUE THREAD

**Issue by 2730gf** [microsoft/nni#4336]
**Describe the issue**:
In NNI2.5，pruning scheduler was released. Both of them have AGP, one is AGPPruner, and the other is AGPTaskGenerator. I want to know the difference between the two?
Also, dependency_aware is not supported in AGPPruner, but it is supported in AGPTaskGenerator. Does this refactoring of the code also take into account that the previous pruning plan does not support dependency?

**Comment by J-shang** [comment]
AGP pruner (v2) is similar to the previous version of the AGP pruner (v1), they have a similar external interface so that users who have used the previous version can use it relatively easily, although their underlying implementation logic is not the same.

In v2, `AGP pruner = AGP task generator + pruning scheduler + basic pruner (e.g. LevelPruner, TaylorFOWeightPruner)`.

Task generator generate the `config_list` used in current iteration, e.g., if there is a linear task generator, your `config_list` passed in is `[{..., 'sparsity': 0.5}]`, `total_iteration=10`, then in each iteration, task generator generate `config_list = [{..., 'sparsity': 0.5 / 10 * current_iteration}]` and package it with the previous iteration pruning model as a task. Pass the task to the scheduler,  and the scheduler uses the basic pruner to perform the task.

So in fact, it is not the `AGPTaskGenerator` support `dependency_aware`, but the basic pruner maybe support `dependency_aware`. If you use `AGPTaskGenerator` with a basic pruner supported `dependency_aware`, then your AGP pruning support `dependency_aware`.

**Comment by 2730gf** [comment]
Great!thanks a lot
