### ISSUE TITLE
why we need LayernameModuleWrapper?

### ISSUE THREAD

**Issue by 2730gf** [microsoft/nni#4419]
**Describe the issue**:
In the process of exporting to TRT, module replacement will be done for pth file, why we need this?
And in LayernameModuleWrapper,  do the following thing:
`inputs = inputs*self.module_bits
        inputs = self.module(inputs)`
module_bits is the index of the module op?
What is the significance of this step, it seems to disrupt the distribution of the input

**Environment**:
- NNI version: 2.5
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by J-shang** [comment]
This step is for marking the config index with its specified module, and this wrapper will never be for inference. Because in onnx model, we need a way to associate onnx node name with the config. With this wrapper, we use a constant node (module_bits) to record the config index. https://github.com/microsoft/nni/blob/64ea284f3b4d27a321c55755ff862c36d753e482/nni/compression/pytorch/quantization_speedup/frontend_to_onnx.py#L51

**Comment by 2730gf** [comment]
Tank you! It's very useful
