### ISSUE TITLE
KubeflowMode support kubeflow mpi-operator ?

### ISSUE THREAD

**Issue by xieydd** [microsoft/nni#525]
Will the KubeflowMode support kubeflow mpi-operator ? @yds05 
And support k8s service is KubeflowMode?

**Comment by yds05** [comment]
Hi, @xieydd , thanks for your question. 

Right now, NNI kubeflow training service just support pytorch-operator and tf-operator, because different operators in Kubeflow have very different schema and behavior.  Supporting mpi-operator is in our plan, but not very urgent. And also, we encourage community users to help us integrate more Kubeflow operators into NNI. 

KubeflowMode is one of k8s services we support. Actually we are developmenting a new training service based on K8S, and will be released in NNI v0.5 in January, 2019.

**Comment by xieydd** [comment]
@yds05 Thank you for your detailed answer 👍 .i will see the way of  supporting pytorch-operator and tf-operator, and find the way of supporting mpi-operator.

**Comment by yds05** [comment]
Awesome! Looking forward to your contributions. Thanks.

**Comment by scarlett2018** [comment]
@xieydd - would you like to plan this item in the coming July release?

**Comment by xieydd** [comment]
@scarlett2018  Yep, I have added the feature for my July schedule

**Comment by xieydd** [comment]
@scarlett2018  Yep, I have added the feature for my July schedule。

**Comment by scarlett2018** [comment]
@xieydd - that's great, we are starting the July Release Planning, will count this item in. And let's keep in sync on the schedule, feel free to raise up any discussions if needed before PR review.
The release draft plan is here: https://github.com/microsoft/nni/issues/1215

**Comment by scarlett2018** [comment]
@xieydd - any update for this issue? thanks.

**Comment by xieydd** [comment]
I am not  focus on  this now in my work, if needed，i will do it in free time.

**Comment by ultmaster** [comment]
No updates. Closing it. Reopen if needed.
