### ISSUE TITLE
Disable WebUI

### ISSUE THREAD

**Issue by chachus** [microsoft/nni#5507]
**Describe the issue**:
I'm trying to use nni on an HPC, but it's not possible to open websockets on it. Is it possible to disable the WebUI? Whenever I run the script it doesn't start as the connection creation fails. Thanks

Error: `requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=42069): Max retries exceeded with url: /api/v1/nni/check-status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14f2697e84f0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Environment**:
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version: 3.9
- PyTorch/TensorFlow version: 
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Comment by liuzhe-lz** [comment]
Please provide nnimanager.log in `~/nni-experiments/<experiment-id>/log`.

**Comment by chachus** [comment]
There is no such file because the experiment doent start since it cant open the webui. There is only experiment.log [experiment.log](https://github.com/microsoft/nni/files/11212077/experiment.log)

**Comment by liuzhe-lz** [comment]
What's the full error message in console? There should be a node.js error before Python exception.

**Comment by chachus** [comment]
Here is the full [experiment_traceback.txt](https://github.com/microsoft/nni/files/11220174/experiment_traceback.txt) from console

**Comment by liuzhe-lz** [comment]
I'm confused...
The node.js process died without generating any output. I cannot understand what happened.

If you are willing to help us debug, please add `print(cmd)` at [this line](https://github.com/microsoft/nni/blob/v2.10/nni/experiment/launcher.py#L158) and check what happens if you directly run that command.

**Comment by chachus** [comment]
The result of the print is this: 

`['/dgx/home/userexternal/amingozz/.conda/envs/nni/lib/python3.9/site-packages/nni_node/node', '--max-old-space-size=4096', '--trace-uncaught', '/dgx/home/userexternal/amingozz/.conda/envs/nni/lib/python3.9/site-packages/nni_node/main.js', '--port', '8080', '--experiment-id', 'pmfrov47', '--action', 'create', '--mode', 'local', '--experiments-directory', '/dgx/home/userexternal/amingozz/nni-experiments', '--log-level', 'info', '--foreground', 'false', '--tuner-command-channel', 'ws://localhost:8080/tuner', '--python-interpreter', '/dgx/home/userexternal/amingozz/.conda/envs/nni/bin/python']`

When i run the command directly nothing happen, it just hangs and doesnt fail or output to console.

I'm running the code on an HPC using SLURM scheduler if this information can help. 
Maybe connection creation is blocked? there is a way to disable the WebUI directly?

**Comment by liuzhe-lz** [comment]
Does it generate `~/nni-experiments/pmfrov47/log/nnimanager.log`? Or does it output anything if append a `--foreground` flag?

The node.js program is simply an ordinary program, nothing special comparing to a Python program. It parses args, inits logging, creates sqlite database, and later at some point listens to HTTP connections. If the listening API call fails, it is supposed to raise an exception.
In this case the problem is it fails to create log files. This happens earlier than anything relates to networking.

The firewall should not be a problem. The failed connection during experiment creation is a localhost IPC channel. Firewalls don't tend to interact with localhost connections. The firewall will make web portal inaccessible, but nothing else (logging, metric database, etc) should be affected.

**Comment by chachus** [comment]
yes this time generated [nnimanager.log](https://github.com/microsoft/nni/files/11230157/nnimanager.log)

**Comment by chachus** [comment]
I tried the command manually again. Then stopped it. Then i tried to relaunch the experiment and somehow it started this time, but then it gave another error the tuner connection. Here are the log files:
[experiment.log](https://github.com/microsoft/nni/files/11230302/experiment.log)
[nnimanager.log](https://github.com/microsoft/nni/files/11230303/nnimanager.log)
