### ISSUE TITLE
Got the error message when I refresh web portal

### ISSUE THREAD

**Issue by lvybriage** [Microsoft/nni#584]
version: v0.5

I run a mnist experiment, and then I don't stop the experiment by the command "nnictl stop".
Because I modify some code so I run the command "source install.sh" to rebuild.
When I refresh the web portal I got the error message.

![error](https://user-images.githubusercontent.com/35484733/50873914-f5eac180-13fc-11e9-8daa-d231177d79f2.png)

**Comment by goooxu** [comment]
@lvybriage I could assume you are a developer, because you want to change the source code.
So, I recommend you follow this [article](https://nni.readthedocs.io/en/latest/SetupNNIDeveloperEnvironment.html) to setup developer environment first, the intention of `source install.sh`  is not used for developer.

**Comment by lvybriage** [comment]
@goooxu Got it, thanks!
