### ISSUE TITLE
How to collect metrics and parameters info

### ISSUE THREAD

**Issue by benchuang11046** [Microsoft/nni#627]
Hi all,
NNI is great project to the research of machine learning.
When I used NNI, I have some questions on NNI usage and config.
* Can I collect the trial and metric information from NNI web API?
* Except HDFS, can I store experiment or triai logs on OpenPAI?

Because I ran many experiments, I tried to integrate these data.
Or NNI has a good solution to solve this problem.
Thanks.

**Comment by QuanluZhang** [comment]
"Can I collect the trial and metric information from NNI web API?":
Yes.
![image](https://user-images.githubusercontent.com/16907603/51363928-29240380-1b15-11e9-9df3-f1d871959b7d.png)

"Except HDFS, can I store experiment or triai logs on OpenPAI?":
OpenPAI has built-in HDFS. You can write log to HDFS in you own code. A better way is: If you want to retrieve trial logs, you can directly download them from WebUI in PAI mode, because NNI downloads those logs to your local machine automatically.

**Comment by benchuang11046** [comment]
Thank for @QuanluZhang answers.

I find three api to get experiment and trial.

http://localhost:8081/api/v1/nni/experiment
http://localhost:8081/api/v1/nni/trial-jobs
http://localhost:8081/api/v1/nni/metric-data
