### ISSUE TITLE
error when using nni with remote computer

### ISSUE THREAD

**Issue by Ling-wei** [Microsoft/nni#719]
My local computer has been correctly installed nni and can run trails in the "\example” folders.
Yet my personal computer has no GPU and I want to use the "machinelist" options in .yml. I log the remote service via ssh and rewrite the .yml file. When I create a new nnictl, it doesn't work right.
I put the log under here. Does anybody have the same question? Help me ples.
```
INFO: Starting restful server...
WARNING: '@nni.get_next_parameter' is deprecated in annotation due to inconvenience. Please remove this line in the trial code.
INFO: Successfully started Restful server!
INFO: Setting remote config...
**ERROR: Failed! Error is: {"error":"EISDIR: illegal operation on a directory, read"}**
```

**Comment by SparkSnail** [comment]
Hi, perhaps this problem happens for there is some  confusion in `/tmp/nni` of remote machine, because nni will read and write files in this folder. Please try `rm -rf /tmp/nni`  in remote machine first, and start a new experiment to try if it works. Notice that nni only support Ubuntu of remote's OS, please let me know if you have any problem.

**Comment by xuehui1991** [comment]
@Ling-wei   Closed for no response,  you can reopen it is not resolved.
